"""add auth fields to users

Revision ID: 07ee51f1082e
Revises: 0004_transparency_fields
Create Date: 2026-08-05 14:06:40.220377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07ee51f1082e'
down_revision: Union[str, None] = '0004_transparency_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sessions_last_active'), table_name='sessions')
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'password_hash')
    op.create_index(op.f('idx_sessions_last_active'), 'sessions', ['last_active'], unique=False)
    # ### end Alembic commands ###
