"""add auth fields to users

Revision ID: 23a403349e69
Revises: 07ee51f1082e
Create Date: 2026-08-08 14:41:49.328792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23a403349e69'
down_revision: Union[str, None] = '07ee51f1082e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
